### ISSUE TITLE
Possible improvement by not using Socket.gethostname

### ISSUE THREAD

**Issue by GP03DHulaki** [logstash-plugins/logstash-filter-metrics#18]
In certain circumstances, "event["message"] = Socket.gethostname" may cost huge delay and render the plugin unusable. I think it might caused by hostname resolving or reverse-resolving. In my logstash use case, I changed it into 

event["message"] = event["host"] || @hostname || Socket.gethostname

@hostname is an arg I added myself.

**Comment by webmstr** [comment]
+1.  Just lost a ton of time to this, and there's no visibility to easily find the cause.  If you hit a lookup failure, why not log it so we'd have some clue?

In our case, logstash had no available DNS, so adding an entry to /etc/hosts worked:

    127.0.0.1  myhost.mydomain.com
