### ISSUE TITLE
Metrics filter stopped working with Logstash/Elastic v2.0 beta

### ISSUE THREAD

**Issue by schmorgs** [logstash-plugins/logstash-filter-metrics#19]
Have this plugin configured in my Logstash filter section : 
```
  metrics {
    meter => "events" 
	add_field => [ "host", "localhost" ]
	add_field => [ "type", "indexer-metric" ]
  }
```

I have output plugins configured for Elasticsearch and stdout 

I can see the metric messages being generated every 5 seconds (stdout), but they never appear in Elasticsearch.

When I run in debug mode, I see that indexing the document is failing, with the reason looking like a dot in the field name is not allowed : 
```
:response=>{"create"=>{"_index"=>"logstash-indexer-metric-2015.10.02", "_type"=>"indexer-metric", "_id"=>"AVAn7w1sB8Lrfh7xNTcR", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"Field name [events.count] cannot contain '.'"}}}, :level=>:warn}
```

Running these versions : 
Elasticsearch 2.0.0-beta2
Logstash 2.0.0-beta1

**Comment by jordansissel** [comment]
Yep, confirmed this is a new feature of Elasticsearch 2.0.0. We'll have to change this filter to compensate.

**Comment by jsvd** [comment]
I'd suggest having a setting like `field_separator` or similar, that defaulted to ".", but could be changed to "_" for those shipping data to es 2.0
this would transform "apache.200.count" into "apache_200_count"
