### ISSUE TITLE
Metrics plugin causes full halt in pipeline

### ISSUE THREAD

**Issue by xrl** [logstash-plugins/logstash-filter-metrics#25]
I have been dockerizing my logstash config and using the docker-library's 1.5.4 image. My pipeline stopped completely at the first message, requiring a hard reset, and I had to track down the issue by commenting out config until the pipeline worked again.

I found the culprit and it's the metrics filter:

```
filter {
  metrics {
    meter => ["events"]
    add_tag => ["metric"]
    flush_interval => 60
    rates => [1]
  }
  if [loghost] == "10.65.248.9" {
    if [cisco-tag] =~ /106015|106023|106100|302013|302014|302015|302016|302020|305011|609001/ {
      mutate {
        add_field => { "host_label" => "%{loghost}"}
      }
      mutate {
        gsub => ["host_label", "\.", "_"]
      }
      metrics {
        meter => ["%{host_label}.%{cisco-tag}"]
        add_tag => ["metric"]
        flush_interval => 60
        rates => [1]
      }
    }
  } # end if
} # end filter
```

what can I do to get my pipeline working again with the metrics filter?

**Comment by hp197** [comment]
The config you quoted should be a working config.

Is there some indication about what is going wring in any log file?
(look in: /var/log/logstash/)
