### ISSUE TITLE
Metrics filter clears all other fields and tags

### ISSUE THREAD

**Issue by vandot** [logstash-plugins/logstash-filter-metrics#37]
After metrics filter log is stripped of all excess fields and tags and you cannot access them.
I need the way to mark a metric that belongs to certain app.
This is log that I want to parse:
<187> Jun  6 06:32:16 staging-server groovi:   [pcm]       INFO: PERF: 0.41ms - /status from 172.17.0.2 (Consul Health Check) [pcm.http.wsgi:120]
With this grok filter:
"<%{POSINT:syslog_pri}> %{SYSLOGBASE}%{SPACE}[%{DATA:environment}]%{SPACE}%{GREEDYDATA:syslog_message}"

Parsing is correct. I add a tag to the log.
mutate { add_tag => [ "%{program}" ] }
program is groovi, and that tag is shown when the log doesn't go thru metrics filter, but when log goes thru metrics there is no more that tag, and also I cannot access %{program} anymore.

**Comment by rvrignaud** [comment]
Relates to https://github.com/elastic/logstash/issues/2880 and https://github.com/logstash-plugins/logstash-filter-metrics/pull/10

**Comment by rvrignaud** [comment]
This bug has been created since 26/Feb/14 : https://logstash.jira.com/browse/LOGSTASH-1942
